### ISSUE TITLE
Fehler bei der Verbindung zum Robi

### ISSUE THREAD

**Issue by bernd70** [Wolbolar/IPSymconRoborock#4]
Wenn ich die Roborock Instanz mit meiner IP und dem Token konfiguriere, bekomme ich eine Fehlermeldung:

`Uncaught TypeError: Argument 2 passed to Roborock::_debug() must be of the type string or null, int given, called in /var/lib/symcon/modules/IPSymconRoborock/Roborock Robot/module.php on line 2338 and defined in /var/lib/symcon/modules/IPSymconRoborock/Roborock Robot/module.php:2724
Stack trace:
#0 /var/lib/symcon/modules/IPSymconRoborock/Roborock Robot/module.php(2338): Roborock-&amp;gt;_debug('Zone numbers', 0)
#1 /var/lib/symcon/modules/IPSymconRoborock/Roborock Robot/module.php(2259): Roborock-&amp;gt;GetNumberZones()
#2 /var/lib/symcon/modules/IPSymconRoborock/Roborock Robot/module.php(1896): Roborock-&amp;gt;FormHead()
#3 /-(3): Roborock-&amp;gt;GetConfigurationForm()
#4 {main}
  thrown in &lt;b&gt;/var/lib/symcon/modules/IPSymconRoborock/Roborock Robot/module.php&lt;/b&gt; on line &lt;b&gt;2724&lt;/b&gt;&lt;br /&gt; (Code: -32603)`

IP uns Token sind imho richtig, mit den gleichen Daten kann ich über Homebridge auf das Gerät zugreifen. Ich habe es sowohl mit dem 32 Zeichen Token als auch mit der 96 Zeichen (ZTOKEN Spalte) Version versucht.

Mein Gerät ist ein Roborock S50.

Was kann ich tun?

Grüße

**Comment by Wolbolar** [comment]
Mal auf den Beta Kanal wechseln und ein Update machen und dann Rückmeldung geben ob der Fehler weg ist.

**Comment by bernd70** [comment]
Damit komme ich ein Stück weiter. Ich komme dann in das Formular, wo ich die verschiedenen Einstellungen machen kann.

Nichtsdestotrotz kommt die Fehlermeldung "Es wurde kein Roborock Staubsaugerroboter unter der IP Adresse und mit dem Token gefunden.". Ich kann dann zwar speichern, aber die erstellte Instanz bekommt auch keine Daten.

**Comment by Wolbolar** [comment]
Ich habe mal strict types vorerst raus genommen, das scheint für Fehler gesorgt zu haben. Kannst Du mit einer aktuelle Beta Version das noch mal probieren. Ansonsten schreibe mal ins Forum Ausgaben vom Debug Fenster falls da was auffällig sein sollte.

**Comment by bernd70** [comment]
Das war es. Jetzt liest er die Daten und lässt sich auch steuern.

Vielen Dank für die Unterstützung.
